name: ma_plante
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  mailer: ^6.4.1
  font_awesome_flutter: ^10.8.0
  flutter_secure_storage: ^9.2.4
  email_validator: ^3.0.0
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.0
  timezone: ^0.10.0
  intl: ^0.20.2
  foundation: ^0.0.5
  http: ^1.2.1
  flutter_dotenv: ^5.0.2
  sensors_plus: ^6.1.1
  fl_chart: ^0.70.2
  light: ^4.1.0
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  flutter_animate: ^4.5.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.3
  cloud_functions: ^5.1.0
  firebase_app_check: ^0.3.1+1
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  tflite_flutter: ^0.11.0
  image: ^4.2.0
  permission_handler: ^11.3.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/images/lÃ©gumes/
    - assets/images/fruits/
    - assets/models/plant_disease_model.tflite
    - assets/models/labels.txt

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21